# Generated by Django 4.1.7 on 2023-02-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
                ('word_class', models.CharField(max_length=1)),
                ('personality', models.CharField(max_length=1)),
                ('sample', models.CharField(max_length=50)),
                ('polish_sample', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('last_question', models.DateTimeField(verbose_name='date published')),
                ('num_answer', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('ratio_correct', models.FloatField(default=0)),
                ('user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.word')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(max_length=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.word')),
            ],
        ),
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_tense', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.word')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ich', models.CharField(max_length=50)),
                ('du', models.CharField(max_length=50)),
                ('er', models.CharField(max_length=50)),
                ('wir', models.CharField(max_length=50)),
                ('ihr', models.CharField(max_length=50)),
                ('sie', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.word')),
            ],
        ),
    ]
