# Generated by Django 4.1.7 on 2023-02-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prular',
            new_name='Plurar',
        ),
    ]
