# Generated by Django 4.1.7 on 2023-02-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0002_rename_prular_plurar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plurar',
            new_name='Plural',
        ),
    ]
