# Generated by Django 4.1.7 on 2023-02-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0004_user_alter_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
