# Generated by Django 4.1.7 on 2023-02-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0005_remove_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wordbase.user'),
            preserve_default=False,
        ),
    ]
