# Generated by Django 4.1.7 on 2023-02-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0006_word_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
