# Generated by Django 4.1.7 on 2023-02-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0007_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='word_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.wordclass'),
        ),
    ]
