# Generated by Django 4.1.7 on 2023-02-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0008_wordclass_alter_word_word_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='er',
            new_name='er_es_sie',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='sie',
            new_name='sie_sie',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='personality',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='word',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbase.person'),
        ),
    ]
