# Generated by Django 4.1.7 on 2023-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0009_rename_er_form_er_es_sie_rename_sie_form_sie_sie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='last_question',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='polish_sample',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='word',
            name='sample',
            field=models.CharField(max_length=150),
        ),
    ]
