# Generated by Django 4.1.7 on 2023-02-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbase', '0011_alter_word_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wordbase.person'),
        ),
    ]
